Refactor
approvers/AHOXA pull request #19
Opened 2020-05-17 17:16 UTC by raiga0310

まじで設計と実装が雑魚なので頑張ります。

2020-05-17 19:36 UTC, raiga0310 commented
構造体`messageContext`を定義:セッション情報とメッセージ情報、メッセージ送信・ファイル送信メソッドを定義
画像生成ハンドラの解体と同時に現時点での新規定義構造体に沿うように改変を加えていきます。
こういうリファクタのために†***単一責任***†を犯してはならないというのがひしひしとわかります

2020-05-18 03:22 UTC, raiga0310 commented
2020年5月18日12時20分現在での進捗
`color`,`help`,`ping`等の処理のリファクタ完了
ハンドラ統一

2020-05-18 04:57 UTC, raiga0310 commented
`morse` の機能も現時点で実装されている`decode` のみですが再設計しました

2020-05-18 11:41 UTC, MikuroXina requested changes
こんなところかなぁ

2020-05-18 11:41 UTC, MikuroXina commented on src/tools.go
> +func morseCodeOperation(optionalArgument string, codeType string) (answerSentence string, Err error) {
おそらく「オプション引数」の意味なんだろうけど、
`optionalArgument` って名前だと「任意の引数」なってしまう気がする

2020-05-18 11:41 UTC, MikuroXina commented on src/tools.go
> +	case "color":
この `switch` - `case` は長すぎる、別オブジェクトに分けよう

2020-05-18 11:41 UTC, shun-shobon submitted a review, later dismissed
お疲れさまです。他の人に任せます。
***†Approve†***

2020-05-18 16:16 UTC, MikuroXina commented on src/tools.go
> +	case "color":
関数に分けるんじゃなくて、その処理をする `interface` を実装したオブジェクトを作って、それを使うようにしてほしいです

2020-05-18 16:16 UTC, MikuroXina commented on src/tools.go
> +func morseCodeOperation(optionalArgument string, codeType string) (answerSentence string, Err error) {
e3e74d4 で確認しました

2020-05-19 11:50 UTC, shun-shobon submitted a review, later dismissed
お疲れさまです。他の人に任せます。
***†Approve†***

2020-05-19 12:02 UTC, MikuroXina requested changes

2020-05-19 12:02 UTC, MikuroXina commented on src/tools.go
> +	case "color":
これは関数に分けてるだけなので、望んでいる解決ではないです
各コマンドの処理を「`struct` となんらかの `interface` の実装」の塊ごとに分けて記述し、
この中で `interface` を介してそれらを利用すれば、
`switch` 自体を消すことができるはずなのでやってみてください

2020-05-20 01:00 UTC, raiga0310 commented
今日から設計考えてみます。まだ理解しきれていないので遅々とした進みになるかもです。

2020-05-22 03:45 UTC, raiga0310 commented
```go
import "fmt"
import "bufio"

type session struct {}
type messageCreate struct {}

type messageContext struct {
	session *session
	message *messageCreate
}

type morseCommand struct {
	messageContext
	table map[string]string
}

type colorCommand struct {
	messageContext
	filedata io.Reader
}

type commandInterface interface {
	Execute()
}
func (morseCtx *colorCommand) Execute (commnad string) (Err error) {
	//TODO
	return nil
}
func (colorCtx *colorCommand) Execute (Err error) {
	//TODO
	return nil
}
```
こんな感じでしょうか。POWERのチャンネルにも記載しておきました。

2020-05-22 03:55 UTC, MikuroXina commented
あとは `morseCommand` や `colorCommand` を構築して `commandInterface` 型として返す関数を作れば OK です
この 「`commandInterface` を作って返す関数」が、「どのコマンドを実行するべきか」判断する関数になります

2020-05-22 11:11 UTC, raiga0310 commented
リファクタを敢行いたします。

2020-06-14 13:27 UTC, MikuroXina requested changes

2020-06-14 13:27 UTC, MikuroXina commented on src/decodeMorse.go
> +func morseCodeOperation(mode string, codeType string) (answerSentence string, Err error) {
codeType って命名が分かりにくいので変えてほしい

2020-06-14 14:47 UTC, MikuroXina requested changes

2020-06-14 14:47 UTC, MikuroXina commented on src/tools.go
> +		}
このコマンド引数を分割/引数の形式を検証/コマンド処理の開始もそれぞれ分けてほしいです
そうすれば、「形式が間違っています」のようなエラーメッセージ出力はあちこちに出てこなくなるはずです

2020-07-06 07:56 UTC, MikuroXina approved these changes

2020-07-06 07:56 UTC, MikuroXina reviewed
押しミス

2020-07-06 08:32 UTC, MikuroXina requested changes

2020-07-06 08:32 UTC, MikuroXina commented on src/tools.go
> +		if len(commandBody) < 2 {
`len(commandBody) != 2` と `len(commandBody) < 2` のどっちかに統一してほしい

2020-07-06 11:51 UTC, raiga0310 reviewed
抽象化は後回しにします。べつPR で対応予定です……。

2020-07-06 11:53 UTC, MikuroXina approved these changes

2020-07-06 14:24 UTC, kawaemon approved these changes

2020-07-06 14:25 UTC, merged

2020-07-06 14:44 UTC, isso0424 reviewed
***MERGED*** but ***SUBMIT REVIEW***

2020-07-06 14:44 UTC, isso0424 commented on src/decodeMorse.go
>  		return
return2連意味なくない?wow wow

2020-07-06 14:44 UTC, isso0424 commented on main.go
> +		return
panic、しませんか

2020-07-06 14:44 UTC, isso0424 commented on src/sendImage.go
> +		return nil, Err
namedReturnValue使わないん...?

2020-07-06 14:44 UTC, isso0424 commented on src/tools.go
> +	return
return 2連 ***再来***

2020-07-06 14:44 UTC, isso0424 commented on src/tools.go
> +	return
2連re(ry

2020-07-06 14:44 UTC, isso0424 commented on src/tools.go
> +			return
case内でまで2連return楽しいね

2020-07-06 14:44 UTC, isso0424 commented on src/tools.go
> +		}
return2連好きすぎん...?

2020-07-06 14:51 UTC, isso0424 commented on main.go
>  	err = discordBrain.Open()
defer discordBrain.Close()が無くない? wow wow