Dockerイメージ作成用DockerfileとGitHub Actions用意
approvers/AHOXA pull request #21
Opened 2020-07-06 09:00 UTC by kawaemon

Containersに移行するために。

2020-07-06 09:49 UTC, raiga0310 submitted a review, later dismissed
初心者目線になりますがこのBot作成者として、レビューします。問題はないかなーってくらいの
***†無責任Approve†***

2020-07-06 12:44 UTC, siketyan requested changes

2020-07-06 12:44 UTC, Siketyan commented on .github/workflows/docker.yaml
> +      - refactor
タグによるトリガもつけないと……
あと refactor はもうトリガにしなくて大丈夫そう

2020-07-06 15:46 UTC, kawaemon commented on .github/workflows/docker.yaml
> +      - refactor
`c791613`で修正

2020-07-06 16:59 UTC, mirror-kt commented
リリース用のbase image、golangだとalpineよりスリムなscratchが使える気がする
ネットワーク系のパッケージ使ってたらdynmic linkになるらしいからstatic linkでコンパイルすれば良さそう

2020-07-06 23:39 UTC, siketyan submitted a review, later dismissed

2020-07-06 23:49 UTC, MikuroXina reviewed
私は Docker のこと何も知らんぞ

2020-07-07 00:53 UTC, siketyan approved these changes

2020-07-07 00:54 UTC, raiga0310 approved these changes

2020-07-07 00:54 UTC, merged