!statusと!resetの実装
approvers/AHOXA pull request #3
Opened 2020-04-17 15:42 UTC by raiga0310

SSIA

2020-04-17 15:58 UTC, isso0424 commented on command/tools.go
> +				}
これswitch-caseでもいいかもしれない

2020-04-17 15:58 UTC, isso0424 commented on command/tools.go
> +					sendMessage(s, c, forbidden)
エラー時にreturnでガードするのはいかが

2020-04-17 15:58 UTC, isso0424 commented on command/tools.go
> +			if strings.Split(m.Content, " ")[0] == "!status" {
statusを `"!status "`にしておけば37行目のifがいらなくなる

2020-04-17 15:58 UTC, isso0424 commented on command/tools.go
>  			}
これはいらないと思う

2020-04-17 15:58 UTC, isso0424 commented on command/tools.go
>  		case strings.HasPrefix(m.Content, fmt.Sprintf("%s", usage)):
command := strings.Split(m.Content, " ")[0][1:]
switch command {
で書くべき
hasPrefixを先にやっておいて!がない場合にreturnとかやってたほうがいい

2020-04-17 15:58 UTC, isso0424 commented on command/tools.go
> +				sendMessage(s, c, wrong)
ここでreturnしておかないと下のsendMessageが動く

2020-04-17 16:15 UTC, raiga0310 commented on command/tools.go
> +					sendMessage(s, c, forbidden)
このばあいは`return`のみで返すということ認識でいいですか.

2020-04-17 16:16 UTC, raiga0310 commented on command/tools.go
>  		case strings.HasPrefix(m.Content, fmt.Sprintf("%s", usage)):
switch-caseを理解していなかった

2020-04-17 16:18 UTC, isso0424 commented on command/tools.go
> +					sendMessage(s, c, forbidden)
そうだね
基本的にエラー処理したらreturnでガードしたほうがいいかもしれない(続行できるならいらないが)

2020-04-17 20:56 UTC, isso0424 submitted a review, later dismissed

2020-04-18 03:59 UTC, Siketyan commented on command/command.go
>  )
このへん const でよくない…？

2020-04-18 03:59 UTC, Siketyan commented on command/sentense.go
>  )
ここも

2020-04-18 04:13 UTC, siketyan requested changes

2020-04-18 04:13 UTC, Siketyan commented on command/sentense.go
>  package command
`sentence`

2020-04-18 04:13 UTC, Siketyan commented on command/sentense.go
> +	usageSentence = "試作段階のBotです。現在実装されているコマンドは、\n!hello: 挨拶をします。\n!name: 発言者の名前を表示します。\n!id: 発言者のIDを表示します。\n!status [Emoji]: 表示名を絵文字にします。\n!reset: 名前をユーザーネームに戻します。"
ここだけ `Sentence` 接尾辞があるのが気になる

2020-04-18 04:13 UTC, Siketyan commented on command/tools.go
> +	commandName := strings.Split(m.Content, " ")[0][1:]
接頭辞が変更される可能性も考えて定数に逃がして部分文字列を取るときに接頭辞の長さを動的に取得したほうがいいと思う

2020-04-18 04:13 UTC, Siketyan commented on command/tools.go
> +			sendMessage(s, c, Emoji + "ですね。" + m.Author.Username + "、行ってらっしゃい。")
fmt.Sprintf 使ったほうがよさそう
https://golang.org/pkg/fmt/#Sprintf

2020-04-18 04:13 UTC, Siketyan commented on command/tools.go
> +			Err :=s.GuildMemberNickname(m.GuildID, m.Author.ID, m.Author.Username + Emoji)
Err だったり err だったりするのでどちらかにしたほうがよさそう．

2020-04-18 04:13 UTC, Siketyan commented on command/tools.go
> +			Err := s.GuildMemberNickname(m.GuildID, m.Author.ID, m.Author.Username)
ここも Err or err に統一

2020-04-18 04:13 UTC, Siketyan commented on command/tools.go
> +			sendMessage(s, c, notify + "、" + m.Author.Username)
同じく Sprintf

2020-04-18 04:15 UTC, raiga0310 commented on command/sentense.go
> +	usageSentence = "試作段階のBotです。現在実装されているコマンドは、\n!hello: 挨拶をします。\n!name: 発言者の名前を表示します。\n!id: 発言者のIDを表示します。\n!status [Emoji]: 表示名を絵文字にします。\n!reset: 名前をユーザーネームに戻します。"
同じpackage内に`usage`があったのでつけていました

2020-04-18 04:16 UTC, Siketyan commented on command/tools.go
> +			if fmt.Sprint(Err) == `HTTP 403 Forbidden, {"message": "Missing Permissions", "code": 50013}` {
err.Error() じゃだめなんかな？
Go 詳しくないのでわからんけど

2020-04-18 04:27 UTC, Siketyan commented on command/sentense.go
> +	usageSentence = "試作段階のBotです。現在実装されているコマンドは、\n!hello: 挨拶をします。\n!name: 発言者の名前を表示します。\n!id: 発言者のIDを表示します。\n!status [Emoji]: 表示名を絵文字にします。\n!reset: 名前をユーザーネームに戻します。"
CommandUsage と SentenceUsage とか接頭辞 / 接尾辞付けるで揃えるかパッケージ分けるかしたほうがよさそう

2020-04-18 05:27 UTC, raiga0310 reviewed
指摘されたところに対応はしました

403エラーの対応については仕様を探してみます

2020-04-18 05:27 UTC, raiga0310 commented on command/tools.go
> +			if fmt.Sprint(Err) == `HTTP 403 Forbidden, {"message": "Missing Permissions", "code": 50013}` {
言われたのは、Goでtry-catchはめんどくさいらしく、提案されたのがこれだった
特定のエラーに対する処理が書けない仕様らしいです(僕も何とも言えない)

2020-04-18 05:27 UTC, raiga0310 commented on command/tools.go
> +			Err :=s.GuildMemberNickname(m.GuildID, m.Author.ID, m.Author.Username + Emoji)
Errに統一しました

2020-04-18 05:27 UTC, raiga0310 commented on command/tools.go
> +			Err := s.GuildMemberNickname(m.GuildID, m.Author.ID, m.Author.Username)
統一しました

2020-04-18 05:32 UTC, Siketyan commented on command/tools.go
> +			if fmt.Sprint(Err) == `HTTP 403 Forbidden, {"message": "Missing Permissions", "code": 50013}` {
や， fmt.Sprint しなくても Err.Error() で string にできるんじゃないかなって

2020-04-18 05:46 UTC, raiga0310 commented on command/tools.go
> +			if fmt.Sprint(Err) == `HTTP 403 Forbidden, {"message": "Missing Permissions", "code": 50013}` {
stringにはなるけど、nil pointerが出ますね…

2020-04-18 09:13 UTC, raiga0310 commented on command/tools.go
> +			if fmt.Sprint(Err) == `HTTP 403 Forbidden, {"message": "Missing Permissions", "code": 50013}` {
@kawaemon さんにアドバイスをいただきました。`Err != nil`の中にネストして処理を投げたいエラーを追加することができました

2020-04-18 10:54 UTC, kawaemon reviewed
特に致命的な問題はありませんでしたが、少し気になる点があったので残しておきます。

2020-04-18 10:54 UTC, kawaemon commented on command/tools.go
> +	commandName := strings.Split(m.Content, " ")[0][1:]
Prefixの変更に備えて、こうしたほうがいいかもしれない？

```suggestion
	commandName := strings.Split(m.Content, " ")[0][len(prefix):]
```

2020-04-18 10:54 UTC, kawaemon commented on command/tools.go
> +		}
この下のcase節でもそうですが、caseの後をブロックにする必要はありません。見やすくするための工夫かもしれませんが。。
```suggestion
		case callName: 
			if m.Member.Nick != "" {
				sendMessage(s, c, m.Member.Nick)
			} else {
				sendMessage(s, c, m.Author.Username)
			}
		
```

2020-04-18 11:10 UTC, kawaemon approved these changes
良いと思います :+1:

2020-04-18 11:38 UTC, siketyan approved these changes

2020-04-18 11:38 UTC, Siketyan commented on sentence/sentence.go
> +package sentence
ファイルの移動が削除と追加の差分に分かれてしまっているので次回から気をつけたほうがいいと思います（追跡できなくなるので）

2020-04-18 11:38 UTC, Siketyan commented on command/tools.go
> +				if Err.Error() == errorBadRequest {
エラー判別の件，たぶん RESTError なので Response のステータスコードでみると良さそうだなって
https://godoc.org/github.com/bwmarrin/discordgo#RESTError

2020-04-18 11:52 UTC, raiga0310 commented on sentence/sentence.go
> +package sentence
わかりました

2020-04-18 11:53 UTC, raiga0310 commented on command/tools.go
> +				if Err.Error() == errorBadRequest {
また考えてみます。今回はこれで。

2020-04-18 11:53 UTC, raiga0310 commented on sentence/sentence.go
> +package sentence
わかりました。

2020-04-18 11:54 UTC, raiga0310 commented on command/tools.go
> +				if Err.Error() == errorBadRequest {
また考えてみます。今回はこのままで。

2020-04-18 11:54 UTC, merged