Herokuへのデプロイのための準備(多分)
approvers/AHOXA pull request #6
Opened 2020-04-19 00:40 UTC by raiga0310

やり方間違ってたら教えてください :bowing_man:

2020-04-19 04:15 UTC, kawaemon submitted a review, later dismissed
いいんじゃないでしょうか？heroku使ったこと無いので保証は出来ませんが。。。

2020-04-19 06:29 UTC, siketyan requested changes
Heroku は Bot をデプロイするためのサービスではなくて Web アプリのための PaaS なので $PORT をリッスンして HTTP で疎通できる状態じゃないと殺されます

2020-04-19 08:36 UTC, mirror-kt commented
> Heroku は Bot をデプロイするためのサービスではなくて Web アプリのための PaaS なので $PORT をリッスンして HTTP で疎通できる状態じゃないと殺されます

別にそんなことはなくて、適切な記述がなされたProcfileを作成すればHTTPサーバー以外を常時起動することができます。

2020-04-19 08:45 UTC, raiga0310 commented
ということはProcfileに`go run main.go`などの走らせる処理を書けばいいということですか？

2020-04-19 08:45 UTC, mirror-kt commented
Procfileがなさそうな気がするので作る必要がありますが

2020-04-19 08:50 UTC, mirror-kt requested changes

2020-04-19 08:50 UTC, mirror-kt commented on Procfile
> +web: go run main.go
これじゃ動かない
worker: change-status-go
とかになると思う

2020-04-19 08:52 UTC, mirror-kt commented on Procfile
> +web: go run main.go
go buildpackがgo installを走らせるので、実行ファイルは既に生成されている(トップディレクトリと同じ名前)
webで指定するとしけちゃんの言う通りポードバインドしないと殺されるので、web以外のworker名を指定する必要がある

2020-04-19 09:03 UTC, raiga0310 commented on Procfile
> +web: go run main.go
一旦Procfileの仕様みてきます

2020-04-19 09:10 UTC, Siketyan commented
> 別にそんなことはなくて、適切な記述がなされたProcfileを作成すればHTTPサーバー以外を常時起動することができます。

今日の知見
https://devcenter.heroku.com/articles/background-jobs-queueing

2020-04-19 09:41 UTC, raiga0310 commented
何か間違っている気もしなくもないけど、とりあえずです

2020-04-19 10:09 UTC, mirror-kt submitted a review, later dismissed
いいと思う(動かなかったらごめんなさい)

2020-04-19 11:38 UTC, siketyan submitted a review, later dismissed
とりあえず一度手動でデプロイしてみて動いたらマージ & CD の設定をすると良いと思います

2020-04-19 11:40 UTC, Siketyan commented on Procfile
> +worker: change-status-go
なんかそんな気がする

```suggestion
worker: ./change-status-go
```

2020-04-20 14:35 UTC, Siketyan commented on heroku.yml
> +    -go
YAML の仕様忘れたけど `-` の後にスペース 1 個いらなかったっけ…？

2020-04-20 14:37 UTC, raiga0310 commented on heroku.yml
> +    -go
いりますね。

2020-07-09 21:17 UTC, closed without merging